name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Render
        uses: https://github.com/content_based_movie_recommender_system/workflows/main.yml
        with:
          renderToken: ${{ secrets.RENDER_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: render/${{ github.repository }}:latest

      - name: Deploy to Render
        uses: renderapp/render-action@1.6.0
        with:
          renderToken: ${{ secrets.RENDER_TOKEN }}
          context: .
          image: render/${{ github.repository }}:latest